export const TABLES = {
  privateTables : ["TABLE_USERS", "TABLE_USERSDATA", "TABLE_ADDRESSES", "TABLE_ORDERS", "TABLE_ORDERITEMS", "TABLE_ORDERSHIPPING", "TABLE_ORDERPAYMENT", "TABLE_PAYMENTTYPESACCOUT"],
  catalogTables : ["TABLE_ITEMS", "TABLE_ITEMSDATA", "TABLE_ITEMCATEGORIES", "TABLE_ITEMCATEGORIESDATA"],
  itemTables : ["TABLE_ITEMS", "TABLE_ITEMSDATA"],
  orderTables : ["TABLE_ORDERS", "TABLE_ORDERITEMS", "TABLE_ORDERSHIPPING", "TABLE_ORDERPAYMENT"],
  forbidenTables : [],
}
