<?php
include("includes/templates/formgeneric.php");
include("includes/templates/formgenerictree.php");
include("includes/templates/alert.php");
include("includes/templates/admnbuts.php");
include("includes/templates/nochildren.php");
include("includes/templates/butopen.php");
include("includes/templates/butclose.php");
include("includes/templates/butedit.php");
include("includes/templates/butdelete.php");
include("includes/templates/butaddnode.php");
include("includes/templates/butvchpos.php");
include("includes/templates/buthchpos.php");
include("includes/templates/butsuccessorder.php");
include("includes/templates/checkout1.php");
?>