<?php
include("includes/templates/alert.php");
include("includes/templates/admnbuts.php");
include("includes/templates/nochildren.php");
include("includes/templates/butopen.php");
include("includes/templates/butclose.php");
include("includes/templates/butedit.php");
include("includes/templates/butdelete.php");
include("includes/templates/butaddnewnode.php");
include("includes/templates/butvchpos.php");
include("includes/templates/buthchpos.php");
include("includes/templates/butsuccessorder.php");
?>